global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
rule_files: []
scrape_configs:
- job_name: consul_servers
  metrics_path: '/v1/agent/metrics'
  params:
    format: ['prometheus']
  static_configs:
  - labels:
      service: 'consul'
    targets:
    - 'snu1.int.efhd.dev:8500'
    - 'snu2.int.efhd.dev:8500'
    - 'snu3.int.efhd.dev:8500'

- job_name: nomad_servers
  metrics_path: '/v1/metrics'
  params:
    format: ['prometheus']
  static_configs:
  - labels:
      service: 'nomad'
    targets:
    - 'snu1.int.efhd.dev:4646'
    - 'snu2.int.efhd.dev:4646'
    - 'snu3.int.efhd.dev:4646'


- job_name: consul
  consul_sd_configs:
  - server: '{{ with $list := service "cnsl~_agent" }}{{ with index $list 0 }}{{ .Address }}:{{ .Port }}{{ end }}{{ end }}'
    scheme: https
    tls_config:
      ca_file: '{{ env `NOMAD_TASK_DIR` }}/interm-ca.pem'
  tls_config:
    ca_file: '{{ env `NOMAD_TASK_DIR` }}/root-ca.pem'
  relabel_configs:
  - source_labels: ['__meta_consul_tags']
    regex: '.*,monitored,.*'
    action: keep
  - source_labels: ['__meta_consul_service']
    target_label: job
  - source_labels: ['__meta_consul_service']
    target_label: service
  - source_labels: ['__meta_consul_dc']
    target_label: dc
  - source_labels: ['__meta_consul_tags']
    regex: '.*,prometheus\.path=([^,]*),.*'
    replacement: '${1}'
    target_label: __metrics_path__
  - source_labels: ['__meta_consul_tags']
    regex: '.*,prometheus\.label\.([^=]*)=([^,]*),.*'
    replacement: '${2}'
    target_label: '${1}'
  - source_labels: ['__meta_consul_tags']
    regex: '.*,https,.*'
    replacement: 'https'
    target_label: '__scheme__'
  - source_labels: ['__meta_consul_node']
    target_label: instance

alerting:
  alertmanagers: []
