#cloud-config
ssh_pwauth: false
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDU4MA87khZngTj9cHA5L/9WZLoYZhb2bEE98bG+qJK36C0jpSKKkMLTNmjKRpZFOI4k2zEs3XGZOYyQHuHbWnpXWBmUIwAPUrvwYvTVGCC18YWEsMKBOeFyTfiIn48nX5MrGvvZk7Og/43evs9zOWQTZxikkutE9T7mR4zPCwI+7deJpvzK+TlFaOoht4c7q40Ygu/LMvBkoSaiY3xtUB/6poBGwzp+ByD9uS56K0aB+IsuW4VP2tl4CmcU0wHXbhj/ZZz6Kb9Oj3osz2gjb6YE78zjESogh/8gIdhIaAyCm9fCw+UWK23sDRcFlNPynY8FTSyC2OIiyEwvsUR/6rNy6RYOZTI1fY7Wh4/3zJ4uf+4DZs7eFPJsF9jIR1E2yXxiIt1O0c7wvAocpLmWIrYTem1hG4Z6MGY7gSIQkOE2sRJH4Y2EZKbbAISiOGqJBG1BII2PszAwzCz7utFAxhNCCm8KuROlMoTOYqAjSC05nHhQAYk8X8NGXtf5ZzPCX5ADgYymgDptBeByT/2dwkgUmCN1qJAyv6kvQq3l7lslLXFg9lBirOB81ImJiIShSJpbjEk4j/RL+kohrLsMBiQlbsU60gezx81bRQUlSM6eTQ94C6Ls2NNKZ0rWE64WQbFwUMoYfrAupgzLkrwZ0r/oZ8SKk4l8J8V5A/hkYA9QQ==
chpasswd:
  expire: false
locale: en_US.UTF-8
locale_configfile: /etc/default/locale
package_update: false
