consul_register:
  services:
  - id: "consului"
    name: "cnsl"
    port: 8500
    tags:
    - "http"
    - "routed"
    - "traefik.http.routers.cnsl.rule=Host(`consul.efthymios.net`)"
  - id: "nomadui"
    name: "nmd"
    port: 4646
    tags: 
    - "http"
    - "routed"
    - "traefik.http.routers.nmd.rule=Host(`nomad.efthymios.net`)"
  - id: "seaweedvol"
    name: "seaweedfs-volume"
    port: 9334
    tags:
    - "http"
    - "monitored"
