consul_register:
  services:
  - id: "consului"
    name: "cnsl"
    port: 8500
    tags:
    - "http"
    - "routed"
    - "traefik.http.routers.cnsl.rule=Host(`consul.efthymios.net`) || Host(`consul.efhd.dev`)"
  - id: "nomadui"
    name: "nmd"
    port: 4646
    tags: 
    - "http"
    - "routed"
    - "traefik.http.routers.nmd.rule=Host(`nomad.efthymios.net`) || Host(`nomad.efhd.dev`)"
  - id: "minio"
    name: "minio"
    port: 9001
    tags:
    - "http"
    - "routed"
