consul_register:
  services:
  - id: "consului"
    name: "cnsl"
    port: 8501
    tags:
    - "http"
    - "routed"
    - "traefik.http.routers.cnsl.rule=Host(`consul.efthymios.net`) || Host(`consul.efhd.dev`)"
    - "traefik.http.routers.cnsl.tls=true"
    - "traefik.http.services.cnsl.loadbalancer.server.scheme=https"
  - id: "nomadui"
    name: "nmd"
    port: 4646
    tags: 
    - "http"
    - "routed"
    - "traefik.http.routers.nmd.rule=Host(`nomad.efthymios.net`) || Host(`nomad.efhd.dev`)"
  - id: "vault"
    name: "vault"
    port: 8200
    tags: 
    - "https"
    - "routed"
    - "monitored"
    - "prometheus.path=/v1/sys/metrics"
    - "traefik.http.routers.vault.tls=true"
    - "traefik.http.services.vault.loadbalancer.server.scheme=https"
  - id: "minio"
    name: "minio"
    port: 9001
    tags:
    - "http"
    - "routed"
