global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: "INFO"
serversTransport:
  rootCAs:
  - "{{ env `NOMAD_TASK_DIR` }}/root-ca.pem"
entryPoints:
  private_web:
    address: "0.0.0.0:80"
    transport:
      lifeCycle:
        graceTimeout: 60
    http:
      redirections:
        entrypoint:
          to: "web_ssl"
          scheme: "https"
  web_ssl:
    address: "0.0.0.0:443"
    transport:
      lifeCycle:
        graceTimeout: 300
    http:
      tls: {}
  traefik:
    address: "0.0.0.0:8080"
  metrics:
    address: "0.0.0.0:8081"
api:
  insecure: true
  dashboard: true
  debug: true
metrics:
  prometheus:
    entryPoint: "metrics"
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
providers:
  consulCatalog:
    defaultRule: '{{ "Host(`{{ normalize .Name }}.efthymios.net`) || Host(`{{ normalize .Name }}.efhd.dev`)" }}'
    endpoint:
      address: "127.0.0.1:8500"
      scheme: "http"
    exposedByDefault: true
    constraints: "Tag(`routed`)"
  file:
    filename: "{{ env `NOMAD_TASK_DIR` }}/fileprovider.yaml"
