- name: restart nomad
  systemd:
    name: "{{nomad_service}}.service"
    state: restarted
    daemon_reload: yes

- name: reload nomad
  systemd:
    name: "{{nomad_service}}.service"
    state: reloaded
