- include_tasks: "{{ ansible_os_family }}.yml"

- name: ensure systemd-resolved listens on the external interface
  lineinfile:
    path: "/etc/systemd/resolved.conf"
    regexp: "DNSStubListenerExtra=.*"
    line: "DNSStubListenerExtra={{ docker_systemd_resolved_address }}"

- name: template docker daemon configuration
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
