- name: install dependencies
  apt:
    name:
    - curl
    - apt-transport-https
    - ca-certificates
    state: "present"

- name: create the docker group
  group:
    name: "docker"
    state: "present"

- name: install docker GPG key
  copy:
    src: "docker-archive-keyring.gpg"
    dest: "{{ docker_keyring_file_path }}"
    owner: root
    group: root
    mode: 0644

- name: add docker repository
  copy:
    content: |
      deb [arch=amd64 signed-by={{ docker_keyring_file_path }}] https://download.docker.com/linux/ubuntu focal stable
    dest: "/etc/apt/sources.list.d/docker.list"
    owner: root
    group: root
    mode: 0644

- name: install the docker packages
  apt:
    name:
    - "docker-ce={{ docker_version }}*"
    - "docker-ce-cli={{ docker_version }}*"
    - "containerd.io={{ docker_containerd_version }}*"
    state: present
    update_cache: true
  notify:
  - docker enable service
  - docker containerd enable service

- name: ensure systemd-resolved listens on the external interface
  lineinfile:
    path: "/etc/systemd/resolved.conf"
    regexp: "DNSStubListenerExtra=.*"
    line: "DNSStubListenerExtra={{ docker_systemd_resolved_address }}"

- name: template docker daemon configuration
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
