- hosts: lifters
  become: true
  vars:
    nomad_version: "1.9.3"
    consul_version: "1.20.1"
    vault_version: "1.18.2"
  vars_files:
  - "vars/consul_acl_tokens.yml"
  - "vars/consul_client.yml"
  - "vars/nomad_client.yml"
  - "vars/vault_agent_client.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: nomad
    tags: nomad
  - role: vault/agent
    tags: vault-agent
