- hosts: lifters
  become: true
  vars:
    nomad_version: "1.6.2"
    consul_version: "1.16.2"
  vars_files:
  - "vars/consul_client.yml"
  - "vars/nomad_client.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: nomad
    tags: nomad
