- hosts: snus
  become: true
  vars:
    nomad_version: "1.6.2"
    consul_version: "1.16.2"
  vars_files:
  - "vars/consul_aio.yml"
  - "vars/consul_services.yml"
  - "vars/nomad_aio.yml"
  - "vars/minio.yml"
  - "vars/vault.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: minio
    tags: minio
  - role: nomad
    tags: nomad
  - role: tailscale
    tags: tailscale
  - role: vault
    tags: vault
