- hosts: snus
  become: true
  vars:
    nomad_version: "1.8.1"
    consul_version: "1.19.0"
  vars_files:
  - "vars/consul_acl_tokens.yml"
  - "vars/consul_aio.yml"
  - "vars/consul_services.yml"
  - "vars/nomad_aio.yml"
  - "vars/minio.yml"
  - "vars/vault.yml"
  - "vars/vault_agent.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: minio
    tags: minio
  - role: nomad
    tags: nomad
  - role: tailscale
    tags: tailscale
  - role: vault/server
    tags: vault
  - role: vault/agent
    tags: vault-agent
