- hosts: snus
  become: true
  vars:
    nomad_version: "1.2.6"
    consul_version: "1.11.4"
    docker_version: "5:20.10.14"
    docker_containerd_version: "1.5.11"
  vars_files:
  - "vars/consul.yml"
  - "vars/consul_services.yml"
  - "vars/nomad.yml"
  - "vars/minio.yml"
  - "vars/moosefs.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: minio
    tags: minio
  - role: nomad
    tags: nomad
  - role: tailscale
    tags: tailscale
