- hosts: snus
  become: true
  vars:
    nomad_version: "1.2.4"
  vars_files:
  - "vars/consul.yml"
  - "vars/consul_services.yml"
  - "vars/nomad.yml"
  - "vars/minio.yml"
  - "vars/moosefs.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: minio
    tags: minio
  - role: moosefs
    tags: moosefs
  - role: nomad
    tags: nomad
  - role: tailscale
    tags: tailscale
