- hosts: snus
  become: true
  vars_files:
  - "vars/consul.yml"
  - "vars/consul_services.yml"
  - "vars/nomad.yml"
  - "vars/minio.yml"
  roles:
  - role: docker
    tags: docker
  - role: consul
    tags: consul
  - role: minio
    tags: minio
  - role: nomad
    tags: nomad
