variable "cloudflare_config" {
  description = "Configuration yml data"
}
variable "cloudflare_tunnel" {
  description = "Autogenerated tunnel json data"
}
variable "cloudflare_cert" {
  description = "Autogenerated argo tunnel certificate data"
}

job "ghost" {
  datacenters = ["homelab"]
  type = "service"

  group "main" {
    network {
      port "http" {
        to = 2368
      }
      port "metrics" {
        to = 8081
      }
    }

    ephemeral_disk {
      sticky  = true
      migrate = true
      size    = 1000
    }

    task "website" {
      driver = "docker"
      kill_timeout = "30s"

      config {
        image = "ghost:4.32"
        ports = ["http"]

        mount {
          type = "bind"
          source = "..${NOMAD_ALLOC_DIR}/data/"
          target = "/var/lib/ghost/content/"
          readonly = false
        }
      }

      service {
        name = "ghost"
        tags = ["http", "routed"]
        port = "http"
        check {
          name = "alive"
          type = "tcp"
          interval = "30s"
          timeout = "2s"
        }
      }

      resources {
        cpu = 500 # 500 Mhz
        memory = 512 # 512MB
      }

      env {
        url = "https://blog.efhd.me"
        admin__url = "http://ghost.efthymios.net"
        database__connection__filename = "${NOMAD_ALLOC_DIR}/data/ghost.db"
        logging__level = "info"
        logging__transports = "[\"stdout\"]"
        privacy__useTinfoil = "true"
      }
    }

    task "cloudflared" {
      driver = "docker"

      config {
        image = "cloudflare/cloudflared:2022.1.3-amd64"
        ports = ["metrics"]
        args = [
          "tunnel",
          "--config=${NOMAD_SECRETS_DIR}/config.yml",
          "--origincert=${NOMAD_SECRETS_DIR}/cert.pem",
          "--no-autoupdate",
          "--metrics=0.0.0.0:8081",
          "run",
        ]
      }

      service {
        name = "cloudflared"
        tags = ["monitored"]
        port = "metrics"
      }

      template {
        data = var.cloudflare_config
        destination = "${NOMAD_SECRETS_DIR}/config.yml"
      }

      template {
        data = var.cloudflare_tunnel
        destination = "${NOMAD_SECRETS_DIR}/tunnel.json"
      }

      template {
        data = var.cloudflare_cert
        destination = "${NOMAD_SECRETS_DIR}/cert.pem"
      }

      resources {
        cpu = 500 # 500 Mhz
        memory = 512 # 512MB
      }
    }
  }
}
