when:
- event: push
  branch: main
  path:
    include:
    - 'docker_images/**/*'
    on_empty: false
matrix:
  IMAGE:
  - backups
  - certbot-dns-cf-consul
steps:
  build:
    image: docker:latest
    commands:
    - cd docker_images/$IMAGE
    - docker build -t docker-registry.efthymios.net/$IMAGE:latest .
    - docker push docker-registry.efthymios.net/$IMAGE:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
