when:
- event: [push, manual]
  branch: main
matrix:
  IMAGE:
  - backups
  - certbot-dns-cf-consul
  - marimo
steps:
- name: build
  image: docker:latest
  commands:
  - cd docker_images/$IMAGE
  - docker build -t docker-registry.efhd.dev/$IMAGE:latest .
  - docker push docker-registry.efhd.dev/$IMAGE:latest
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
