auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 15m
  max_transfer_retries: 0
schema_config:
  configs:
    - from: 2022-01-16
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
    shared_store: s3
  aws:
    s3: 'http://{{ key "loki/minio/access_key_id" }}:{{ key "loki/minio/secret_access_key" }}@minio.service.consul:9000/loki'
    region: ""
    s3forcepathstyle: true
compactor:
  working_directory: /data/compactor
  shared_store: s3
  compaction_interval: 1h
  retention_enabled: true
  retention_delete_delay: 2h
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 7d
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
